<a href="https://colab.research.google.com/github/khushigarg20/RL/blob/main/Q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
R = np.matrix([[-1,-1,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,-1,0,-1,-1],
               [-1,0,0,-1,0,-1],
               [-1,0,0,-1,-1,100],
               [-1,0,-1,-1,0,100]])

In [21]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [22]:
Q = np.matrix(np.zeros([6,5]))
Q

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
gamma = 0.8
initial_state = 1 

In [24]:
def available_actions(state):
  current_state_row = R[state,]
  av_act = np.where(current_state_row >=0)[1]
  return av_act

In [25]:
available_act = available_actions(initial_state)

In [26]:
available_act

array([3, 5])

In [27]:
def sample_next_action(available_actions_range):
  next_action = int(np.random.choice(available_act,1))
  return next_action

In [28]:
action = sample_next_action(available_act)

In [29]:
action

5

In [37]:
def update(current_state,action,gamma):
  max_index = np.where(Q[action,] == np.max(Q[action,]))[1]

  if max_index.shape[0]>1:
    max_index=int(np.random.choice(max_index,size=1))
  else:
    max_index = int(max_index)
  max_value = Q[action,max_index]


  Q[current_state,action] = R[current_state,action] + gamma*max_value


update(initial_state,action,gamma)

IndexError: ignored

In [14]:
Q

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [38]:
for i in range(10000):
  current_state = np.random.randint(0,int(Q.shape[0]))
  available_act = available_actions(current_state)
  action = sample_next_action(available_act)
  update(current_state,action,gamma)

 

IndexError: ignored

In [15]:
print("Trained Q matrix:")
print(Q/np.max(Q)*100)