<a href="https://colab.research.google.com/github/khushigarg20/RL/blob/main/Q_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
R = np.matrix([[-1,-1,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,-1,0,-1,-1],
               [-1,0,0,-1,0,-1],
               [-1,0,0,-1,-1,100],
               [-1,0,-1,-1,0,100]])

In [2]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [3]:
Q = np.matrix(np.zeros([6,5]))
Q

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
gamma = 0.8
initial_state = 1 

In [5]:
def available_actions(state):
  current_state_row = R[state,]
  av_act = np.where(current_state_row >=0)[1]
  return av_act

In [6]:
available_act = available_actions(initial_state)

In [7]:
available_act

array([3, 5])

In [8]:
def sample_next_action(available_actions_range):
  next_action = int(np.random.choice(available_act,1))
  return next_action

In [9]:
action = sample_next_action(available_act)

In [10]:
action

3

In [16]:
def update(current_state,action,gamma):
  max_index = np.where(Q[action,] == np.max(Q[action,]))[1]

  if max_index.shape[0]>1:
    max_index=int(np.random.choice(max_index,size=1))
  else:
    max_index = int(max_index)
  max_value = Q[action,max_index]


  Q[current_state,action] = R[current_state,action] + gamma*max_value


update(initial_state,action,gamma)

IndexError: ignored

In [12]:
Q

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [14]:
for i in range(10000):
  current_state = np.random.randint(0,int(Q.shape[0]))
  available_act = available_actions(current_state)
  action = sample_next_action(available_act)
  update(current_state,action,gamma)

print("Trained Q matrix:")
print(Q/np.max(Q)*100)

IndexError: ignored

In [ ]:
current_state = 1
steps = [current_state]

while current_state != 5:
  next_step_index = np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
  if next_step_index.shape[0]>1:
    next_step_index = int(np.random.choice(next_step_index,size=1))
  else:
    next_step_index = int(next_step_index)

  steps.append(next_step_index)
  current_state = next_step_index


print("selected path:")
print(steps)